export { ICoordinate, ICoordinatePoint } from './coordinate.interface';
export { ILogin } from './login.interface';
export { ILoginReturn } from './login-return.interface';
export { IExtraDataToSave } from './extra-data-to-save.interface';
export { IInfiniteScroll } from './infinite-scroll.interface';
export { IPaginationOptions } from './paginate-options.interface';
export { IReqWithCookies } from './req-with-cookies.interface';
export { IUserReq } from './user-req.interface';
export { IAddressComponent } from './address-component.interface';
export { IDatabaseCoordinate } from './database-coordinate.interface';
export { ICookieInterceptor } from './cookie.interceptor';
export { IResponse, IResponseWithData } from './response.interface';
export { ITokenGenerate } from './token-generate.interface';
export { IRefreshToken, IGoogleLogin } from './refresh-token.interface';
export { ILoginResponse, IProviderSocialMedia } from './login-response.interface';
export { IFileInterface } from './file.interface';
export * from './social-medias.interface';