version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: lineup
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    command: npm run start:prod
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: 123
      DB_NAME: lineup
      DB_ENTITIES: core/entities/*.entity.js
      DB_MIGRATIONS: core/migrations/*.js
    depends_on:
      - db
    volumes:
      - .:/app
    restart: always

volumes:
  pgdata:
