/**
 * Stable keys for public notification copy ({@link notificationsPublic}).
 */
export enum NotificationContentScenarioEnum {
  USER_CHANGE_PASSWORD = 'USER_CHANGE_PASSWORD',
  BUSINESS_CHANGE_PASSWORD = 'BUSINESS_CHANGE_PASSWORD',
  NEW_PRODUCT_REVIEW = 'NEW_PRODUCT_REVIEW',
  DISCOUNT_ACTIVATED = 'DISCOUNT_ACTIVATED',
  DISCOUNT_EXPIRED = 'DISCOUNT_EXPIRED',
  PRODUCT_LOW_STOCK = 'PRODUCT_LOW_STOCK',
}
