import {
    Business,
    BusinessRole,
    Catalog,
    File,
    Permission,
    Product,
    ProductFile,
    ProductVariation,
    Role,
    RolePermission,
    Token,
    User,
    UserRole,
    Location,
    SocialNetwork,
    SocialNetworkBusiness,
    ProductReaction
} from '.';

export const entities = [
    User,
    Role,
    UserRole,
    Token,
    Permission,
    RolePermission,
    File,
    Business,
    BusinessRole,
    Product,
    ProductFile,
    ProductReaction,
    ProductVariation,
    Catalog,
    Location,
    SocialNetwork,
    SocialNetworkBusiness,
]